### PR TITLE
Adjust for pytest and add pkg to tests

### PR DESCRIPTION
**Pull request by danwagnerco**
This PR implements a few changes that make running the test suite with [py.test](http://pytest.org/latest/) a cinch:
1. Test file names were all changed to `test_*.py`
2. Test files adjusted to add the package to the PATH (`sys.path.append("../bowshock/")`)
3. The `__init__.py` file handles all the `import` statements

Here are the tweaks in action on a vanilla Precise32 box (though I didn't record ALL of the tests running haha):

bowshock

### CODE REVIEW

**Comment by danwagnerco** [comment]
This time I updated the `.travis.yml` file, but it looks like the `NASA_API_KEY` environment variable is not found. How do you populate this key for Travis?

**Comment by danwagnerco** [comment]
Hey @emirozer -- quick check-in on this, can you advise on your preferred method for configuring Travis with the ENV `NASA_API_KEY` variable?

Thanks and have a good weekend!

**Comment by emirozer** [comment]
Hi @danwagnerco thank you very much for your PR! 

I will check it in a few hours and provide feedback!

**Comment by emirozer** [comment]
I am testing your branch locally and it seems to work just fine...
That api key is an environment var in the Travis setup i made...
Will update further, going to do some tests in Travis...

**Comment by danwagnerco** [comment]
Sounds great -- let me know if there are any adjustments I can make in the meantime. Thanks!

**Comment by emirozer** [comment]
i am almost certain now that the problem's origin is travis.. I am merging your pr..

**Pull request merged**
